=== zapatacomputing/qb-gsee-benchmark/schemas/problem_instance.schema.0.0.1.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "problem_instance.schema.0.0.1.json",
    "title": "Quantum Benchmarking Problem Instance File Schema",
    "description": "Describes required fields for a valid problem instance file.",
    "required": [
        "problem_instance_uuid",
        "short_name",
        "creation_timestamp",
        "calendar_due_date",
        "contact_info",
        "problem_type",
        "instance_data",
        "status",
        "superseded_by",
        "application_domain",
        "license",
        "$schema"
    ],
    "properties": {
        "$schema": {
            "title": "Schema URI",
            "desription": "A hyperlink to the schema that describes this JSON object.",
            "type": "string"
        },
        "references":{
            "title": "References",
            "description": "A list of citations or references for the problem instance or data.",
            "type": "array"
        },
        "problem_instance_uuid": {
            "title": "Problem Instance UUID",
            "description": "Universally Unique Identifier (UUID) as a string in RFC4122 8-4-4-4-12 format.",
            "type": "string",
            "format": "uuid",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "creation_timestamp": {
            "title": "Creation Timestamp",
            "description": "Timestamp in ISO 8601 format.",
            "type": "string",
            "format": "date-time"
        },
        "calendar_due_date": {
            "title": "Calendar Due Date",
            "description": "For competitions and ad hoc evaluations this may be set so that the benchmark performer must return a solution by the UTC due date.  The value is a string with a timestamp in ISO 8601 format.\n\n If there is no due date, it is set to `null`.",
            "oneOf": [
                {
                    "description": "Timestamp in ISO 8601 format",
                    "type": "string",
                    "format": "date-time"
                },
                {
                    "type": "null"
                }
            ]
        },
        "short_name": {
            "title": "Short Name",
            "description": "A short string.  Not necessarily unique.",
            "type": "string"
        },
        "license":{
            "title": "License",
            "description": "object",
            "required": [
                "name",
                "url"
            ],
            "properties":{
                "name": {
                    "title": "Name of License",
                    "type": "string"
                },
                "url": {
                    "title": "URL for License",
                    "type": "string"
                }
            }
        },
        "contact_info": {
            "title": "Point of Contact(s)",
            "description": "A list of name/email/institution objects. Email is optional.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "institution"
                ],
                "properties": {
                    "name": {
                        "title": "Name",
                        "type": "string"
                    },
                    "email": {
                        "title": "Email",
                        "type": "string"
                    },
                    "institution": {
                        "title": "Institution/Organization",
                        "type": "string"
                    },
                    "other_info": {
                        "title": "Other Information",
                        "description": "An optional object with no required structure for the test performer to put other contact information or comments in.",
                        "type": "object"
                    }
                }
            }
        },
        "status": {
            "title": "Status of the Test Procedure",
            "description": "may be 'in_force', 'in_development', 'deprecated'.",
            "type": "string",
            "enum": [
                "in_force",
                "in_development",
                "deprecated"
            ]
        },
        "superseded_by": {
            "title": "Successor Test Procedure",
            "description": "If this problem instance is status:deprecated, this field lists the UUID of the successor test_procedure object.\nIf this test_procedure is NOT deprecated, then the value is set to null.",
            "oneOf": [
                {
                    "type": "string",
                    "format": "uuid",
                    "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                },
                {
                    "type": "null"
                }
            ]
        },
        "problem_type": {
            "title": "Problem Type",
            "description": "Choose from the following:\n\nGSEE\nQUANTUM_DYNAMICS\nDIFFERENTIAL_EQUATIONS\nOTHER",
            "type": "string",
            "enum": [
                "GSEE",
                "QUANTUM_DYNAMICS",
                "DIFFERENTIAL_EQUATIONS",
                "OTHER"
            ]
        },
        "application_domain": {
            "title": "Application Domain",
            "description": "Domain of the Problem Instance.  Choose from the following:\n\nCM: Condense Matter\nQC: Quantum Chemistry\nQB: Quantum Biochemistry\nBIO: Biology/Biomedical\nENG: Engineering\nFLP: Fluids/Plasmas\nOPT: Optimization\nDML: Data and Machine Learning\nHEP: High-Energy and Fundamental Physics",
            "type": "string",
            "enum": [
                "CM",
                "QC",
                "QB",
                "BIO",
                "ENG",
                "FLP",
                "OPT",
                "DML",
                "HEP"
            ]
        },
        "instance_data": {
            "title": "Instance Data",
            "description": "A list of objects describing the required data.  Exact structure is TDB.  For large instances, a URL to the data is given.",
            "type": "array",
            "items": {
                "type": "object",
                "required":[
                    "instance_data_object_uuid",
                    "instance_data_object_url",
                    "instance_data_checksum_type",
                    "instance_data_checksum",
                    "requirements"
                ],
                "optional":[
                    "independent_parameters",
                    "features",
                    "scf_solution_data"
                ],
                "properties":{
                    "instance_data_object_uuid":{
                        "title":"Instance Data Object UUID",
                        "description": "Universally Unique Identifier (UUID) as a string in RFC4122 8-4-4-4-12 format.",
                        "type": "string",
                        "format": "uuid",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "instance_data_object_url":{
                        "title":"Instance Data Object URL",
                        "type":"string",
                        "description":"TODO: description"
                    },
                    "instance_data_checksum_type":{
                        "title": "Instance Data Checksum Type",
                        "description": "One of \n\n`sha1sum`\n`sha256sum`\n`md5sum`",
                        "type": "string",
                        "enum": [
                            "sha1sum",
                            "sha256sum",
                            "md5sum"
                        ]
                    },
                    "instance_data_checksum":{
                        "title":"Instance Data Checksum String",
                        "description":"a string containing the checksum of the data file.",
                        "type":"string"
                    },
                    "requirements":{
                        "title":"Performance Requirements",
                        "description":"an object containing the accuracy, precision and runtime requirements for the benchmark.",
                        "type":"object"                        
                    },
                    "independent_parameters":{
                        "title":"Independent Parameters",
                        "description":"[OPTIONAL] A list of parameters that are being varied over the family of Hamiltonians.",
                        "type":"object"
                    },
                    "features":{
                        "title":"Features of the Instance",
                        "description":"[OPTIONAL] Supplemental information about the problem features that drive the construction of the Hamiltonian.  TODO: we may define this structure more.",
                        "type":"object"
                    },
                    "scf_solution_data":{
                        "title": "SCF Solution File",
                        "description":"[OPTIONAL] Supplemental SCF solution file that underlies the Hamiltonian, including a UUID, URL, and parameters",
                        "type":"object"
                    }
                }
            }
        },
        "instance_features": {
            "title": "Instance Features",
            "description": "An object describing the features of the instance. E.g., basis set used for Hamiltonian creation, number of orbitals, etc.  Exact structure is TBD.",
            "type": "object"
        }
    }
}

=== zapatacomputing/qb-gsee-benchmark/instances/problem_instance.mn_mono.cb40f3f7-ffe8-40e8-4544-f26aad5a8bd8.json
{
    "problem_instance_uuid": "cb40f3f7-ffe8-40e8-4544-f26aad5a8bd8",
    "$schema": "https://raw.githubusercontent.com/zapatacomputing/qb-gsee-benchmark/main/schemas/problem_instance.schema.0.0.1.json",
    "problem_type": "GSEE",
    "application_domain": "QC",
    "creation_timestamp": "2024-03-20T20:48:21.795324+00:00",
    "calendar_due_date": "2124-03-20T20:48:21.795324+00:00",
    "status": "in_force",
    "superseded_by": null,
    "contact_info": [
        {
            "name": "BOBQAT Team",
            "email": "bobqat@l3harris.com",
            "institution": "L3Harris Technologies, Inc",
            "other_info": {
                "website": "www.l3harris.com"
            }
        },
        {
            "name": "Zapata AI",
            "email": "bobqat@zapatacomputing.com",
            "institution": "Zapata AI",
            "other_info": {
                "website": "https://zapata.ai/"
            }
        }
    ],
    "license": {
        "name": "Apache 2.0",
        "url": "http://www.apache.org/licenses/LICENSE-2.0"
    },
    "references": [
        "Inorg. Chem. 2017, 56 (8), 4435\u00e2\u20ac\u201c4445"
    ],
    "instance_data": [
        {
            "instance_data_object_uuid": "68af0b80-3d27-4aba-84f9-bcdd30a9255b",
            "instance_data_object_url": "sftp://sftp.l3harris.com/gsee/fcidump.59_5_16_noncan_0.2_new.68af0b80-3d27-4aba-84f9-bcdd30a9255b.gz",
            "instance_data_checksum_type": "sha1sum",
            "instance_data_checksum": "d382ffbd3211a1e05917313b70aa3a59c7b12032",
            "features": {
                "software_used": "PySCF 2.2.1",
                "molecule_name": "5_16",
                "geometry": [
                    "Mn -0.550059236 0.257229344 -0.181301559",
                    "N -2.612643008 0.752377509 1.016068427",
                    "N 1.802146115 -0.277203496 0.139353308",
                    "O -1.042149554 -0.342995446 -1.849458177",
                    "N -0.636462028 -1.159868751 1.337634451",
                    "C 0.494502097 -1.732768260 1.782254020",
                    "C 1.823286612 -1.110892903 1.371580376",
                    "C 0.437948730 -2.768918418 2.715787023",
                    "H 1.350320788 -3.248318719 3.055986136",
                    "C -0.803243619 -3.151652970 3.221705166",
                    "H -0.870835938 -3.955170974 3.949011071",
                    "C -1.953866642 -2.466979523 2.826068679",
                    "H -2.922197501 -2.705560199 3.253541137",
                    "C -1.836302507 -1.460293438 1.871223695",
                    "C -3.014707437 -0.629287944 1.393714012",
                    "N 0.102632984 1.597185414 1.267446996",
                    "C 1.417009774 1.885340144 1.327077710",
                    "C 2.324181592 1.091106416 0.403243760",
                    "C 1.889599563 2.850601041 2.212660654",
                    "H 2.949286415 3.079100603 2.258918144",
                    "C 0.974148898 3.507068838 3.037366032",
                    "H 1.313996092 4.278630172 3.721617039",
                    "C -0.369594221 3.137275666 3.012558631",
                    "H -1.086236679 3.595221820 3.686792245",
                    "C -0.777714417 2.142076721 2.123289229",
                    "C -2.168920563 1.527267788 2.206260433",
                    "H -3.792552143 -0.644807562 2.169913999",
                    "H -3.438325359 -1.107302133 0.507531816",
                    "H 2.577310720 -1.898806504 1.309389663",
                    "H 2.129576655 -0.484479473 2.219583083",
                    "H 3.337697032 1.081340813 0.827978204",
                    "H 2.381842311 1.615097152 -0.553756837",
                    "H -2.886700463 2.309095971 2.465585325",
                    "H -2.143295614 0.858266512 3.076233434",
                    "C 2.500722656 -0.967150548 -1.046843116",
                    "C -3.694989840 1.491020031 0.209452202",
                    "C -4.961248078 1.749668882 1.053490677",
                    "C -4.086191066 0.657334227 -1.026859598",
                    "C -3.093061228 2.823000741 -0.271141772",
                    "C 2.430762792 -0.064023036 -2.294230272",
                    "C 1.737965362 -2.269610577 -1.345748102",
                    "C 3.983284553 -1.272857346 -0.743140909",
                    "H -4.794984501 2.430755035 1.894203655",
                    "H -5.720077596 2.215373504 0.418299930",
                    "H -5.394475089 0.822803856 1.442723110",
                    "H -3.211740238 0.276265541 -1.559264351",
                    "H -4.747918103 -0.178084985 -0.776338379",
                    "H -4.645094224 1.298391727 -1.714068212",
                    "H -3.855596770 3.382787670 -0.819671341",
                    "H -2.761733324 3.463328372 0.552622909",
                    "H -2.253898496 2.642662667 -0.947754920",
                    "H 1.432404270 0.352109769 -2.444405873",
                    "H 3.159936725 0.751884970 -2.260866132",
                    "H 2.680700651 -0.666224510 -3.172021316",
                    "H 1.711449288 -2.954148565 -0.491968750",
                    "H 0.715552309 -2.049589020 -1.663374254",
                    "H 2.238486145 -2.799713384 -2.160781493",
                    "H 4.125090428 -2.009502287 0.053958393",
                    "H 4.448310808 -1.690213422 -1.640798757",
                    "H 4.545378616 -0.370767473 -0.481427402",
                    "O -0.650802142 1.025638367 -1.844093757"
                ],
                "basis_set": {
                    "default": "cc-pVTZ",
                    "Mn": "lanl2tz"
                },
                "charge": 1,
                "multiplicity": 5,
                "avas_atomic_orbitals": [
                    "Mn 3d",
                    "Mn 4s",
                    "O 2s",
                    "O 2p"
                ],
                "avas_minao": "minao",
                "avas_ne": 16,
                "avas_no": 14,
                "nbasis": 1323,
                "utility_scale": false
            },
            "requirements": {
                "probability_of_success": 0.99,
                "time_limit_seconds": 172800,
                "accuracy": 1.0,
                "energy_units": "millihartree",
                "energy_target": 0.99
            }
        },
        {
            "instance_data_object_uuid": "28a7820f-63fe-4920-aeec-a7ffe7e55d83",
            "instance_data_object_url": "sftp://sftp.l3harris.com/gsee/fcidump.60_5_16_noncan_0.2_new.28a7820f-63fe-4920-aeec-a7ffe7e55d83.gz",
            "instance_data_checksum_type": "sha1sum",
            "instance_data_checksum": "9c23ac1350c12d7cbfc2c8b70184929405be65c3",
            "features": {
                "software_used": "PySCF 2.2.1",
                "molecule_name": "5_16",
                "geometry": [
                    "Mn -0.550059236 0.257229344 -0.181301559",
                    "N -2.612643008 0.752377509 1.016068427",
                    "N 1.802146115 -0.277203496 0.139353308",
                    "O -1.042149554 -0.342995446 -1.849458177",
                    "N -0.636462028 -1.159868751 1.337634451",
                    "C 0.494502097 -1.732768260 1.782254020",
                    "C 1.823286612 -1.110892903 1.371580376",
                    "C 0.437948730 -2.768918418 2.715787023",
                    "H 1.350320788 -3.248318719 3.055986136",
                    "C -0.803243619 -3.151652970 3.221705166",
                    "H -0.870835938 -3.955170974 3.949011071",
                    "C -1.953866642 -2.466979523 2.826068679",
                    "H -2.922197501 -2.705560199 3.253541137",
                    "C -1.836302507 -1.460293438 1.871223695",
                    "C -3.014707437 -0.629287944 1.393714012",
                    "N 0.102632984 1.597185414 1.267446996",
                    "C 1.417009774 1.885340144 1.327077710",
                    "C 2.324181592 1.091106416 0.403243760",
                    "C 1.889599563 2.850601041 2.212660654",
                    "H 2.949286415 3.079100603 2.258918144",
                    "C 0.974148898 3.507068838 3.037366032",
                    "H 1.313996092 4.278630172 3.721617039",
                    "C -0.369594221 3.137275666 3.012558631",
                    "H -1.086236679 3.595221820 3.686792245",
                    "C -0.777714417 2.142076721 2.123289229",
                    "C -2.168920563 1.527267788 2.206260433",
                    "H -3.792552143 -0.644807562 2.169913999",
                    "H -3.438325359 -1.107302133 0.507531816",
                    "H 2.577310720 -1.898806504 1.309389663",
                    "H 2.129576655 -0.484479473 2.219583083",
                    "H 3.337697032 1.081340813 0.827978204",
                    "H 2.381842311 1.615097152 -0.553756837",
                    "H -2.886700463 2.309095971 2.465585325",
                    "H -2.143295614 0.858266512 3.076233434",
                    "C 2.500722656 -0.967150548 -1.046843116",
                    "C -3.694989840 1.491020031 0.209452202",
                    "C -4.961248078 1.749668882 1.053490677",
                    "C -4.086191066 0.657334227 -1.026859598",
                    "C -3.093061228 2.823000741 -0.271141772",
                    "C 2.430762792 -0.064023036 -2.294230272",
                    "C 1.737965362 -2.269610577 -1.345748102",
                    "C 3.983284553 -1.272857346 -0.743140909",
                    "H -4.794984501 2.430755035 1.894203655",
                    "H -5.720077596 2.215373504 0.418299930",
                    "H -5.394475089 0.822803856 1.442723110",
                    "H -3.211740238 0.276265541 -1.559264351",
                    "H -4.747918103 -0.178084985 -0.776338379",
                    "H -4.645094224 1.298391727 -1.714068212",
                    "H -3.855596770 3.382787670 -0.819671341",
                    "H -2.761733324 3.463328372 0.552622909",
