=== zapatacomputing/qb-gsee-benchmark/schemas/solution.schema.0.0.1.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "solution.schema.0.0.1.json",
    "title": "Quantum Benchmarking Solution File Schema",
    "description": "Describes required fields for a valid solution file.",
    "required": [
        "solution_uuid",
        "problem_instance_uuid",
        "short_name",
        "creation_timestamp",
        "contact_info",
        "solution_data",
        "compute_hardware_type",
        "compute_details",
        "digital_signature",
        "$schema"
    ],
    "properties": {
        "$schema": {
            "title": "Schema URI",
            "desription": "A hyperlink to the schema that describes this JSON object.",
            "type": "string"
        },
        "solution_uuid": {
            "title": "Solution UUID",
            "description": "The UUID of the solution being submitted as a string in 8-4-4-4-12 format.",
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "problem_instance_uuid": {
            "title": "Problem Instance UUID",
            "description": "The UUID of the problem instance that the solution is based on.",
            "type": "string",
            "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
        },
        "creation_timestamp": {
            "title": "Creation Timestamp",
            "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
            "type": "string",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
        },
        "short_name": {
            "title": "Short Name",
            "description": "A short string.  Not necessarily unique.",
            "type": "string"
        },
        "contact_info": {
            "title": "Point of Contact(s)",
            "description": "A list of name/email/institution objects.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "email",
                    "institution"
                ],
                "properties": {
                    "name": {
                        "title": "Name",
                        "type": "string"
                    },
                    "email": {
                        "title": "Email",
                        "type": "string"
                    },
                    "institution": {
                        "title": "Institution/Organization",
                        "type": "string"
                    },
                    "other_info": {
                        "title": "Other Information",
                        "description": "An optional object with no required structure for the test performer to put other contact information or comments in.",
                        "type": "object"
                    }
                }
            }
        },
        "is_resource_estimate": {
            "title": "Is Resource Estimate",
            "description": "A boolean indicating whether the solution is an estimate of a solver's performance. If this field is not set, it is assumed to be false.",
            "type": "boolean"
        },
        "solution_data": {
            "title": "Solution Data",
            "description": "A list of objects describing the data.  Exact structure is TDB.  For large instances, a URL to the data is given.",
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "instance_data_object_uuid",
                    "run_time"
                ],
                "properties": {
                    "instance_data_object_uuid": {
                        "title": "Instance Data Object UUID",
                        "description": "TODO: description",
                        "type": "string",
                        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
                    },
                    "energy": {
                        "title": "Energy",
                        "description": "The Ground State Energy.",
                        "type": "number"
                    },
                    "energy_units": {
                        "title": "Energy Units",
                        "description": "units.  E.g., `kcal/mol`",
                        "type": "string"
                    },
                    "error_bound": {
                        "title": "Error Bound",
                        "description": "Bound on the absolute energy error.",
                        "type": "number",
                        "minimum": 0
                    },
                    "confidence_level": {
                        "title": "Confidence Level",
                        "description": "Probability that the absolute energy error is less than the error bound.",
                        "type": "number",
                        "minimum": 0,
                        "maximum": 1
                    },
                    "run_time": {
                        "title": "Wall Clock Runtime",
                        "description": "A breakdown of start/stop wall clock time(s) reported according to ISO 8601 in UTC and duration in seconds.  run_time is broken down into (1) overall_time, (2) preprocessing_time, (3), algorithm_run_time, and (4) postprocessing_time.  See descriptions of each object.",
                        "type": "object",
                        "required": [
                            "overall_time",
                            "preprocessing_time",
                            "algorithm_run_time",
                            "postprocessing_time"
                        ],
                        "properties": {
                            "overall_time": {
                                "title": "Overall Wall Clock Time",
                                "description": "Includes all pre/postprocessing times and algorithm_run_time.",
                                "type": "object",
                                "required": [
                                    "seconds"
                                ],
                                "properties": {
                                    "wall_clock_start_time": {
                                        "title": "Wall Clock Start Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "wall_clock_stop_time": {
                                        "title": "Wall Clock Stop Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "seconds": {
                                        "title": "Duration in Seconds",
                                        "description": "The number of seconds that has elapsed between start/stop times reported.",
                                        "type": "number",
                                        "minimum": 0
                                    }
                                }
                            },
                            "preprocessing_time": {
                                "title": "Preprocessing Wall Clock Time",
                                "description": "The time required to load any data into an idle machine before running an algorithm.",
                                "type": "object",
                                "required": [
                                    "seconds"
                                ],
                                "properties": {
                                    "wall_clock_start_time": {
                                        "title": "Wall Clock Start Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "wall_clock_stop_time": {
                                        "title": "Wall Clock Stop Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "seconds": {
                                        "title": "Duration in Seconds",
                                        "description": "The number of seconds that has elapsed between start/stop times reported.",
                                        "type": "number",
                                        "minimum": 0
                                    }
                                }
                            },
                            "algorithm_run_time": {
                                "title": "Algorithm Run Time",
                                "description": "The start/stop times for how long the software/algorithm ran.",
                                "type": "object",
                                "required": [
                                    "seconds"
                                ],
                                "properties": {
                                    "wall_clock_start_time": {
                                        "title": "Wall Clock Start Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "wall_clock_stop_time": {
                                        "title": "Wall Clock Stop Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "seconds": {
                                        "title": "Duration in Seconds",
                                        "description": "The number of seconds that has elapsed between start/stop times reported.",
                                        "type": "number",
                                        "minimum": 0
                                    },
                                    "compute_node_run_time_breakdown": {
                                        "title": "Compute Node Run Time Breakdown",
                                        "description": "Breakdown of algorithm_run_time across multiple nodes if a cluster of multiple machines was utilized.\n\nThis object is optional.  There is no required structure for this object."
                                    }
                                }
                            },
                            "postprocessing_time": {
                                "title": "Postprocessing Wall Clock Time",
                                "description": "The time required measure or read out any data from the machine.  .",
                                "type": "object",
                                "required": [
                                    "seconds"
                                ],
                                "properties": {
                                    "wall_clock_start_time": {
                                        "title": "Wall Clock Start Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "wall_clock_stop_time": {
                                        "title": "Wall Clock Stop Time",
                                        "description": "Timestamp in ISO 8601 format in UTC (note the `Z`).\n\nExamples:  \n`2022-12-25T18:00:02.223Z`,\n`2022-12-25T07:18:45Z`",
                                        "type": "string",
                                        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d+)?Z$"
                                    },
                                    "seconds": {
                                        "title": "Duration in Seconds",
                                        "description": "The number of seconds that has elapsed between start/stop times reported.",
                                        "type": "number",
                                        "minimum": 0
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "compute_hardware_type": {
            "title": "Compute Hardware Type",
            "description": "Type of device the algorithm is actually run on.  Choose from:\n\n`classical_computer` \n`quantum_computer` \n`hybrid_classical_quantum_computer` \n`other`.",
            "type": "string",
            "enum": [
                "classical_computer",
                "quantum_computer",
                "hybrid_classical_quantum_computer",
                "other"
            ]
        },
        "compute_details": {
            "title": "Compute Hardware & Software Details",
            "description": "Details on the hardware and software (algorithm) used by the test performer. Exact structure is TBD.",
            "type": "object"
        },
        "digital_signature": {
            "title": "Digital Signature",
            "description": "This is created by the benchmark performer and their private key.  It is calculated over the TBD object.  If this is not implemented, it may be set to null",
            "anyOf": [
                {
                    "type": "object"
                },
                {
                    "type": "null"
                }
            ]
        }
    },
    "if": {
        "required": ["is_resource_estimate"],
        "properties": {
            "is_resource_estimate": {
                "const": true
            }
        }
    },
    "then": {
        "properties": {
            "solution_data": {
                "items": {
                    "required": [
                        "error_bound",
                        "confidence_level"
                    ]
                }
            }
        }
    },
    "else": {
        "properties": {
            "solution_data": {
                "items": {
                    "required": [
                        "energy"
                    ]
                }
            }
        }
    }
}

=== zapatacomputing/qb-gsee-benchmark/solution_files/coarse_set/cb40f3f7-ffe8-40e8-4544-f26aad5a8bd8_sol_30d863a7-ffde-40f9-8107-af771ec986b5.json
{
    "$schema": "https://raw.githubusercontent.com/zapatacomputing/qb-gsee-benchmark/refs/heads/main/instances/schemas/solution.schema.0.0.1.json",
    "solution_uuid": "30d863a7-ffde-40f9-8107-af771ec986b5",
    "problem_instance_uuid": "cb40f3f7-ffe8-40e8-4544-f26aad5a8bd8",
    "creation_timestamp": "2024-10-02T19:23:17.097271Z",
    "short_name": "QPE",
    "is_resource_estimate": true,
    "contact_info": [
        {
            "name": "Max Radin",
            "email": "max.radin@zapata.ai",
            "institution": "Zapata AI"
        }
    ],
    "solution_data": [
        {
            "instance_data_object_uuid": "68af0b80-3d27-4aba-84f9-bcdd30a9255b",
            "run_time": {
                "overall_time": {
                    "seconds": 130648434.19662397
                },
                "preprocessing_time": {
                    "seconds": 92.24001598358154
                },
                "algorithm_run_time": {
                    "seconds": 130648341.95660798
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "28a7820f-63fe-4920-aeec-a7ffe7e55d83",
            "run_time": {
                "overall_time": {
                    "seconds": 1664073932.1223369
                },
                "preprocessing_time": {
                    "seconds": 127.2850890159607
                },
                "algorithm_run_time": {
                    "seconds": 1664073804.8372478
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "f738fcd6-7ddc-4d70-8ff9-4019e3718b04",
            "run_time": {
                "overall_time": {
                    "seconds": 133173800.78035574
                },
                "preprocessing_time": {
                    "seconds": 18.053699731826782
                },
                "algorithm_run_time": {
                    "seconds": 133173782.726656
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "6e2bf415-6a69-4b36-ba0f-780a11cb7c0b",
            "run_time": {
                "overall_time": {
                    "seconds": 1827250460.5177379
                },
                "preprocessing_time": {
                    "seconds": 110.68720984458923
                },
                "algorithm_run_time": {
                    "seconds": 1827250349.830528
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "027490ba-34f9-4340-89ab-27fd110d2821",
            "run_time": {
                "overall_time": {
                    "seconds": 133699950.46700683
                },
                "preprocessing_time": {
                    "seconds": 34.24659085273743
                },
                "algorithm_run_time": {
                    "seconds": 133699916.22041598
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "bae2da57-6a69-483e-95bc-b77f72ebfba8",
            "run_time": {
                "overall_time": {
                    "seconds": 1822049254.3327522
                },
                "preprocessing_time": {
                    "seconds": 109.89768028259277
                },
                "algorithm_run_time": {
                    "seconds": 1822049144.435072
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "72343006-774e-4192-b481-fa840ed25573",
            "run_time": {
                "overall_time": {
                    "seconds": 133068577.38371417
                },
                "preprocessing_time": {
                    "seconds": 21.355810165405273
                },
                "algorithm_run_time": {
                    "seconds": 133068556.027904
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        },
        {
            "instance_data_object_uuid": "ea55abec-8253-445d-85fa-914948b5e5a5",
            "run_time": {
                "overall_time": {
                    "seconds": 1827701433.7916307
                },
                "preprocessing_time": {
                    "seconds": 112.39502286911011
                },
                "algorithm_run_time": {
                    "seconds": 1827701321.3966079
                },
                "postprocessing_time": {
                    "seconds": 0
                }
            },
            "error_bound": 0.001,
            "confidence_level": 0.99
        }
    ],
    "compute_hardware_type": "quantum_computer",
    "compute_details": {
        "description": "Double factorized QPE resource estimates based on methodology of arXiv:2406.06335. Uses PyLIQTR logical resource estimates with BenchQ footprint analysis. Ground-state overlap assumed to be 0.8 and double-factorized truncation threshold to be 1e-3 Ha. Note that the truncation error is not included in the error bounds and that the SCF compute time is not included in the preprocessing time."
    },
    "digital_signature": null
}
